### ISSUE TITLE
ERROR Except thrown while pulling user data:'module' object has no attribute 'MYSQL_HOST'

### ISSUE THREAD

**Issue by xiaobailong24** [fsgmhoward/shadowsocks-py-mu#26]
Nov 04 17:24:24 INFO -----------------------------------------
Nov 04 17:24:24 INFO Multi-User Shadowsocks Server Starting...
Nov 04 17:24:24 INFO Current Server Version: 3.1.1-14-ge06bfd4

Nov 04 17:24:24 INFO Now using MySQL Database as the user interface
Nov 04 17:24:24 INFO Now starting manager thread...
Nov 04 17:24:29 INFO Now starting user pulling thread...
Nov 04 17:24:29 ERROR Except thrown while pulling user data:'module' object has no attribute 'MYSQL_HOST'

**Comment by fsgmhoward** [comment]
Apologies. Please ignore the previous answer. Can you please check whether `config.py` exists and there is a line of `MYSQL_HOST = 'xxx'` inside.

**Comment by xiaobailong24** [comment]
What a foolish!  I miss **'M'** in "MYSQL_HOST". 
Thank you very much. I love this project and your coding style!!!

**Comment by xiaobailong24** [comment]
And another error when I install it on my other VPS:
```
Nov 04 23:16:38 INFO -----------------------------------------
Nov 04 23:16:38 INFO Multi-User Shadowsocks Server Starting...
Nov 04 23:16:38 INFO Current Server Version: 3.1.1-14-ge06bfd4

Nov 04 23:16:38 INFO Now using MySQL Database as the user interface
Nov 04 23:16:38 INFO Now starting manager thread...
Nov 04 23:16:38 ERROR Can not bind to manager address: [Errno 99] Cannot assign requested address
Nov 04 23:16:43 INFO Now starting user pulling thread...
Nov 04 23:16:46 WARNING Exception thrown when sending command: timed out
Nov 04 23:16:46 ERROR Except thrown while pulling user data:No JSON object could be decoded
Nov 04 23:16:48 INFO Now starting user pushing thread...
Nov 04 23:16:50 ERROR Except thrown while pushing user data:timed out
Nov 04 23:17:20 WARNING Exception thrown when sending command: timed out
Nov 04 23:17:20 ERROR Except thrown while pulling user data:No JSON object could be decoded
```

MANAGE_BIND_IP = 'global_ip'
**global_ip** is the ip of VPS installed ss-panel

**Comment by zuoruizhi** [comment]
Try another manager port .also can use 127.0.0.1 for MANAGE_BIND_IP . By the way REBOOT your VPS .

**Comment by fsgmhoward** [comment]
Actually the manage_bind_ip is the IP the SS Server's manager daemon listen on. It should be 127.0.0.1 in most cases.

Basically the server consists of 3 parts, `dbtransfer.py` in charge of pulling/pushing user data from db/mu-api, `manager.py` in charge of starting/terminating the thread of servers (you can understand it as server for each port is separated), and `tcprelay` and `udprelay` i/c of relaying the data. Since they are 3 separate parts, when `dbtransfer.py` get user info from DB/mu-api, it contacts the manager by locally listened port. For example your manager listen on 127.0.0.1:5555, `dbtransfer.py` will send a command like `{"add": xxxx}` to manager so that manager can know that it needs to start a new server/port.

MANAGE_BIND_IP is the IP where manager listen on. It can only receive command from db thread when it binds on 127.0.0.1. If you want to use ss-panel with API support, you should set API_ENABLED to True and change the settings in the API section.

**Comment by xiaobailong24** [comment]
@fsgmhoward  @zuoruizhi  OK, I know. Thanks for your full answer!
